### ISSUE TITLE
dnsdist closes congested DNS-over-QUIC streams with INTERNAL_ERROR

### ISSUE THREAD

**Issue by Spiffyk** [PowerDNS/pdns#13631]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: dnsdist 
 - Issue type: Bug report

### Short description

While testing [my implementation of DNS-over-QUIC](https://gitlab.nic.cz/knot/shotgun/-/merge_requests/75) in [DNS Shotgun](https://dns-shotgun.readthedocs.io) against `dnsdist`, I have found that it closes a large number of streams with an `INTERNAL_ERROR` app code.

### Environment

 - Operating system: OpenSUSE Tumbleweed
 - Software version: `master` - 5012710e403dbf6c93451b6fc159bc83b0fbaf79
 - Software source: Compiled myself

### Steps to reproduce

1. Send high-volume DNS-over-QUIC traffic to dnsdist, e.g. using DNS Shotgun.

### Expected behaviour
Pretty much 100% of the queries should be answered in a localhost setting.

### Actual behaviour
A large number of the queries are lost because dnsdist closes the streams with an `INTERNAL_ERROR` app code.

### Other information

After inspecting the code, the culprit seems to be that the `quiche_conn_stream_send` function returns the value `-1` (`QUICHE_ERR_DONE`), which is because the stream is congested, [as per the Quiche documentation](https://github.com/cloudflare/quiche/blob/8e64c0670835d2005dfb10c743382c9fd52f56d6/quiche/src/lib.rs#L4550). This causes `dnsdist` to lose a lot of legitimate queries in a high-volume traffic scenario.

When `quiche_conn_stream_send` returns `QUICHE_ERR_DONE`, `dnsdist` should defer sending the reply to a later time at which it gets notified that the stream is writable again.

**Comment by rgacogne** [comment]
Hi! Thank for reporting this! @chbruyand has noticed this as well, we are looking into it.

**Comment by rgacogne** [comment]
@Spiffyk I'm currently testing a patch that should fix the issue, and I was wondering if I could easily reproduce your tests? I can build DNS shotgun from your branch, but is there a way to generate similar PCAP(s) to the one(s) you are using?

**Comment by Spiffyk** [comment]
@rgacogne I use actual captures and can't share those PCAPs, but there is a `pcap/generate-const-qps.lua` script that I think *should* do the job.

**Comment by rgacogne** [comment]
Understood, I'll look into it. Thanks!

**Comment by Spiffyk** [comment]
INTERNAL_ERROR is gone, but I'm still getting some strange results, especially on long-lived connections.

![latency](https://github.com/PowerDNS/pdns/assets/2039454/82bb2a9f-63b5-4d1b-960e-8257444258b7)

The chart above contains latencies - a test of Shotgun DoQ in comparison with DoT against dnsdist (commit af62fb146d58a64da8c8c41e14da3d1ad2be3c3a), on pure localhost. Dnsdist is set to send a REFUSED RCode for everything (to simply test baseline performance of QUIC) using `addAction(AllRule(), RCodeAction(DNSRCode.REFUSED))`.

By `default`, Shotgun reuses connections and sends multiple queries over them. In a `no-idle` scenario, Shotgun creates a new connection for *each query*. Everything on the 2000 milliseconds mark has been lost (2000 ms is the default timeout). Note that the chart uses a logarithmic scale.

For reference, here is a chart when tested against a [DoQ echo server written in Go](https://github.com/ns1labs/doq-proxy/pull/11) under the same conditions (without DoT because this server is DoQ-only):

![latency](https://github.com/PowerDNS/pdns/assets/2039454/f33a2390-3f1c-411b-9572-efe143929fe3)

Shall I open another issue?

**Comment by rgacogne** [comment]
Thanks! So there is clearly a bug somewhere in our stack. Given that this issue has not been referenced in a release/changelog yet I'm just going to re-open it.

**Comment by rgacogne** [comment]
I believe this is now fixed, but please let me know if you think otherwise!

**Comment by Spiffyk** [comment]
Testing with [this PCAP](https://gitlab.nic.cz/knot/shotgun/uploads/91f07600c143a39793e02756ccb2557f/3k_60s_sanitized.pcap) kindly provided by @tkrizek, I still get quite a few losses. Would you try it on your end, please?

![latency](https://github.com/PowerDNS/pdns/assets/2039454/fdc1a38b-cdbe-4aa2-9937-aec5f03e9586)
![response-rate](https://github.com/PowerDNS/pdns/assets/2039454/0274c568-7be6-407b-a88f-30635cf48dd3)

**Comment by rgacogne** [comment]
With the trace you are providing DNS shotgun tries to reuse a DoQ connection that has been idle for longer than dnsdist allows it: 5 seconds by default, which might not be a very good default come to think of it..
Would you mind trying with `idleTimeout=30` on `addDOQLocal`, ie  something like that:
```lua
addDOQLocal("192.0.2.1:853",{"server.pem" }, {"server.key" }, {idleTimeout=30})
```

In my own tests this yields:
![latency](https://github.com/PowerDNS/pdns/assets/1086257/badf1bac-6b72-44cf-96a8-9dc5785bdeea)
![response-rate](https://github.com/PowerDNS/pdns/assets/1086257/604c854f-ba99-4003-8ceb-23798dfa547a)

**Comment by Spiffyk** [comment]
Right! I'm now thinking maybe the actual correct way to handle this would be to adjust Shotgun's idle timeout to the *minimum of the local and remote idle timeouts*? Shotgun's idle timer is also adjustable. It currently does not take the server's idle timer into account, although it *does* receive that information from the server.

When I do that locally, it does seem to be better (although there are still some as of yet unexplained losses when 0-RTT/resumption is disabled):

![latency](https://github.com/PowerDNS/pdns/assets/2039454/42dbea76-cd6e-44fb-adfb-fa26669c7460)
![response-rate](https://github.com/PowerDNS/pdns/assets/2039454/71253183-7e06-4f51-b68e-fdb5281c416e)

**Comment by rgacogne** [comment]
> I'm now thinking maybe the actual correct way to handle this would be to adjust Shotgun's idle timeout to the _minimum of the local and remote idle timeouts_?

That sounds like a good idea to me, yes! I'm still going to ponder increasing the default in dnsdist, but it would be awesome if DNS shotgun can adapt automatically.

> When I do that locally, it does seem to be better (although there are still some as of yet unexplained losses when 0-RTT/resumption is disabled):

Thanks, it means something might still be of on our side. I'll see if I can reproduce, but it might not be before Monday.

**Comment by Spiffyk** [comment]
> Thanks, it means something might still be of on our side

Actually, no, I seem to have fixed it! I moved the timer adjustment from the `handshake_confirmed` callback over to `handshake_completed`, which seems to have done the trick. I'll push the patch to Shotgun momentarily and have it reviewed to see whether there are any objections to this adjustment. It might actually fix a few more compatibility issues with other servers as well, but I have yet to test that.

Thanks for the cooperation, Remi!

![latency](https://github.com/PowerDNS/pdns/assets/2039454/93b8f76d-28c8-4484-ad34-087ca15f8caa)
![response-rate](https://github.com/PowerDNS/pdns/assets/2039454/7566ddf7-7dd0-45b7-96da-d2e474cecf12)

**Comment by rgacogne** [comment]
Wonderful :-)
Thanks a lot for your work on DNS shotgun, by the way, it's a great tool!

**Comment by Spiffyk** [comment]
Credit for that goes to @tkrizek, shout out to him! (I only did the QUIC part) :slightly_smiling_face:
