### ISSUE TITLE
PDNS 4 on Ubuntu Server 16.04

### ISSUE THREAD

**Issue by Patdundee** [PowerDNS/pdns#4232]
Hi Guys 
Upgraded to Ubuntu 16.04 and updated PDNS to V4 (Big problem for me)

Everything worked fine on the old 3.x versions in 14.04

Here is the error i get when starting pdns monitor

Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail

This happens everytime i try to run pdns

here is the pdns.local.gmysql.conf

```
# MySQL Configuration
#
# Launch gmysql backend
launch=gmysql
# gmysql parameters
gmysql-host=localhost
gmysql-dbname=pdns
gmysql-user=MyUSerName
gmysql-password=MyPassowrd
```
Everything is up to date on the server
Any ideas on how to fix would be great :)

**Comment by pieterlexis** [comment]
Hi,

This was fixed before the 4.0.0 final release, however, Ubuntu 16.04 has an alpha in the repositories. Please use [our repos](https://repo.powerdns.com) for an up to date 4.0.0 package.

We are in the process of getting Ubuntu to update their packages to a more recent 4.0.0 release.

**Comment by Habbie** [comment]
This is a known issue in the pre-release v4 that Ubuntu has. Our repo has a newer, fixed version.

On July 25, 2016 3:19:04 PM GMT+02:00, Patdundee <notifications@github.com> wrote:
>Hi Guys 
>Upgraded to Ubuntu 16.04 and updated PDNS to V4 (Big problem for me)
>
>Everything worked fine on the old 3.x versions in 14.04
>
>Here is the error i get when starting pdns monitor
>
>Backend reported condition which prevented lookup (GSQLBackend lookup
>query: Attempt to bind more parameters than query has: SELECT
>content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE
>disabled=0 and type=? and name=?) sending out servfail
>
>This happens everytime i try to run pdns
>
>here is the pdns.local.gmysql.conf
>
>```
># MySQL Configuration
>#
># Launch gmysql backend
>launch=gmysql
># gmysql parameters
>gmysql-host=localhost
>gmysql-dbname=pdns
>gmysql-user=MyUSerName
>gmysql-password=MyPassowrd
>```
>Everything is up to date on the server
>Any ideas on how to fix would be great :)
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/4232

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by Patdundee** [comment]
Hi 
I still get the issue
I have completely removed pdns server and pdns mysql 
followed the instructions for the soiurces list addition and the preferences

ran the following 

```
curl https://repo.powerdns.com/FD380FBB-pub.asc | sudo apt-key add - &&
sudo apt-get update &&
sudo apt-get install pdns-server pdns-backend-mysql
```
but still get the same issue

created my pdns.local.gmysql.conf with the following

```
# MySQL Configuration
#
# Launch gmysql backend
launch=gmysql
# gmysql parameters
gmysql-host=localhost
gmysql-dbname=pdns
gmysql-user=MyUSerName
gmysql-password=MyPassword

```
Where would i be going wrong

:)

**Comment by pieterlexis** [comment]
can you please show the output of `dpkg -l pdns*` and your full log please?

**Comment by Patdundee** [comment]
wow thats interesting here is the dpkg result after completely removing and installing using apt-get install 

```
root@dns2:/home/auspat# dpkg -l pdns
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  pdns           <none>       <none>       (no description available)
root@dns2:/home/auspat# un  pdns           <none>       <none>       (no descrip                                                                             tion available)
bash: syntax error near unexpected token `<'

```

here is the log using srvice pdns monitor

```
service pdns monitor                                                                                                                 Jul 25 15:45:16 Reading random entropy from '/dev/urandom'
Jul 25 15:45:16 Loading '/usr/lib/i386-linux-gnu/pdns/libgmysqlbackend.so'
Jul 25 15:45:16 [gmysqlbackend] This is the gmysql backend version 4.0.0-alpha2 reporting
Jul 25 15:45:16 Loading '/usr/lib/i386-linux-gnu/pdns/libbindbackend.so'
Jul 25 15:45:16 [bind2backend] This is the bind backend version 4.0.0-alpha2 reporting
Jul 25 15:45:16 This is a standalone pdns
Jul 25 15:45:16 UDP server bound to 0.0.0.0:53
Jul 25 15:45:16 Unable to enable timestamp reporting for socket
Jul 25 15:45:16 UDPv6 server bound to [::]:53
Jul 25 15:45:16 TCP server bound to 0.0.0.0:53
Jul 25 15:45:16 TCPv6 server bound to [::]:53
Jul 25 15:45:16 PowerDNS Authoritative Server 4.0.0-alpha2 (C) 2001-2016 PowerDNS.COM BV
Jul 25 15:45:16 Using 32-bits mode. Built using gcc 5.3.1 20160330.
Jul 25 15:45:16 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
Jul 25 15:45:16 Set effective group id to 116
Jul 25 15:45:16 Set effective user id to 108
Jul 25 15:45:16 Creating backend connection for TCP
% Jul 25 15:45:16 gmysql Connection successful. Connected to database 'pdnstest' on 'localhost'.
Jul 25 15:45:16 [bindbackend] Parsing 0 domain(s), will report when done
Jul 25 15:45:16 [bindbackend] Done parsing domains, 0 rejected, 0 new, 0 removed
Jul 25 15:45:16 About to create 3 backend threads for UDP
Jul 25 15:45:16 gmysql Connection successful. Connected to database 'pdnstest' on 'localhost'.
Jul 25 15:45:16 gmysql Connection successful. Connected to database 'pdnstest' on 'localhost'.
Jul 25 15:45:16 gmysql Connection successful. Connected to database 'pdnstest' on 'localhost'.
Jul 25 15:45:16 Done launching threads, ready to distribute questions
Jul 25 15:45:24 Exception: Parsing record content (try 'pdnsutil check-zone'): while parsing IPv6 address: '109.224.221.5' is invalid
Jul 25 15:45:24 Exception building answer packet (Parsing record content (try 'pdnsutil check-zone'): while parsing IPv6 address: '109.224.221.5' is invalid) sending out servfail
Jul 25 15:45:24 Exception building answer packet (stoul) sending out servfail
Jul 25 15:45:25 Exception building answer packet (stoul) sending out servfail
Jul 25 15:45:38 Exception building answer packet (stoul) sending out servfail
Jul 25 15:45:38 Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail
Jul 25 15:45:38 Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail
Jul 25 15:45:38 Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail
Jul 25 15:45:40 Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail
Jul 25 15:45:41 Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail
Jul 25 15:45:41 Backend reported condition which prevented lookup (GSQLBackend lookup query: Attempt to bind more parameters than query has: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?) sending out servfail

```

**Comment by pieterlexis** [comment]
`Jul 25 15:45:16 PowerDNS Authoritative Server 4.0.0-alpha2 (C) 2001-2016 PowerDNS.COM BV`

This is not from our repos (we ship 4.0.0 at the moment). Did you also set the preferences in `/etc/apt/preferences.d`?

**Comment by Patdundee** [comment]
Hi

went to 

> https://repo.powerdns.com/

selected Ubuntu 16.04 "Xenial Xerus"
then selected PowerDNS Authoritative Server - version 4.0.X

added the following to sources list
`deb http://repo.powerdns.com/ubuntu xenial-auth-40 main`

added the following to apt/preferences.d
```
Package: pdns-*
Pin: origin repo.powerdns.com
Pin-Priority: 600
```

Ran these commands

```
curl https://repo.powerdns.com/FD380FBB-pub.asc | sudo apt-key add
sudo apt-get update
sudo apt-get install pdns-server
```

**Comment by pieterlexis** [comment]
So for some reason your system does not install our version from the repos. can you run (and show me the output of) `sudo apt-get update; sudo apt-get dist-upgrade; sudo install pdns-server pdns-backend-mysql; sudo dpkg -l pdns-server`

**Comment by Habbie** [comment]
It appears to be i386?

On July 25, 2016 5:03:57 PM GMT+02:00, Pieter Lexis <notifications@github.com> wrote:
>So for some reason your system does not install our version from the
>repos. can you run (and show me the output of) `sudo apt-get update;
>sudo apt-get dist-upgrade; sudo install pdns-server pdns-backend-mysql;
>sudo dpkg -l pdns-server`
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/PowerDNS/pdns/issues/4232#issuecomment-234980336

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by Patdundee** [comment]
Sure

```
apt-get update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://gb.archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Hit:4 http://gb.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:5 http://repo.powerdns.com/ubuntu xenial-auth-40 InRelease
Fetched 95.7 kB in 0s (132 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://repo.powerdns.com/ubuntu xenial-auth-40 InRelease' doesn't support architecture 'i386'
```
```
apt-get dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```
```
apt-get install pdns-server pdns-backend-mysql
Reading package lists... Done
Building dependency tree
Reading state information... Done
pdns-backend-mysql is already the newest version (4.0.0~alpha2-3build1).
pdns-server is already the newest version (4.0.0~alpha2-3build1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

```
sudo dpkg -l pdns-server
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-=======================================================================
ii  pdns-server                       4.0.0~alpha2-3build1  i386                  extremely powerful and versatile nameserver

```

**Comment by Patdundee** [comment]
interesting line here in update
Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://repo.powerdns.com/ubuntu xenial-auth-40 InRelease' doesn't support architecture 'i386'

**Comment by pieterlexis** [comment]
ah yes, @Habbie is correct. We don't have i386 repositories, so either use an amd64 machine, compile 4.0.0 yourself or re-build the package from [Debian Sid](https://packages.debian.org/source/sid/pdns) for i386

**Comment by Patdundee** [comment]
Yup just checked :( 32 bit 
This is going to be new for me lol never done this before

so from Debian Sid i would select the following

pdns-backend-mysql (which version should i download from there)
pdns-server (Which version of pdns-server should i download from there)

(so far as i can see i can add the following to my sources list (deb ftp.uk.debian.org/debian)
can i get them downloaded and installed via apt-get with the addition to the sources file?
P

**Comment by pieterlexis** [comment]
I think the easiest solution is to use an AMD64 machine and not just take packages from another distro, if you're bound to i386, install Debian Sid and use the pdns package from Debian.

**Comment by Patdundee** [comment]
as this is an urgent install due to one of the dns servers being offline, it may be easier to re install ubuntu 14,04 If i do that is there a way i can get the legacy pdns server and pdns backend mysql 3.3?

Just hope my other dns server does not go down in the meantime
P

**Comment by pieterlexis** [comment]
yeah, sure, if that works on your previous/still working server. do it

**Comment by Patdundee** [comment]
Hi Pieter
Many thanks for yesterday
I installed pdns server with mysql on a new server last night and followed all instructions as above. It still had an error and came up with something like no support for the system even the on uname m it shows x86 64

Are you around today if i re install again and produce the same reports and logs as above from the new system to have a look for me please
P

**Comment by pieterlexis** [comment]
Hi Pat, we (and the community) would love to help, but GitHub is not the place for this type of support. Please use [our pdns-users mailinglist](https://www.powerdns.com/mailing-lists.html) or join [#powerdns on the oftc.net](irc://irc.oftc.net/#powerdns) IRC network ([web-based client](https://webchat.oftc.net/?channels=powerdns&uio=MT11bmRlZmluZWQb1)).

**Comment by Patdundee** [comment]
Hi Pieter
Many thanks :)
P
