### ISSUE TITLE
uppercase name records in mysql backend dnssec wildcard proof failure

### ISSUE THREAD

**Issue by at0rvk** [PowerDNS/pdns#5370]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

With gmysql backend zone records that contain uppercase characters in the _name_ field cause dnssec wildcard proof validation failures.

### Environment

 - Operating system: Debian Jessie 8.8
 - Software version: 4.0.3
 - Software source: PowerDNS repository
 - Backend: gmysql

### Steps to reproduce

1. Have record with uppercase character and a wildcard record and dnssec
2. dig some.random.query.example.com againt validating resolver

### Expected behaviour

NOERROR and get the IP address from the wildcard record.

### Actual behaviour

SERVFAIL
[1496414022] libunbound[12696:0] info: validate(positive): sec_status_bogus
some.random.query.example.com has address 192.0.2.100
validation failure <some.random.query.example.com A IN>: wildcard proof failed from 192.0.2.1

**Comment by pieterlexis** [comment]
Note, should be fixed by b91cfe5c069df975176f5fd944540f72fc5d01bb in the coming Authoritative 4.0.4 release

**Comment by Habbie** [comment]
> Note, should be fixed by b91cfe5 in the coming Authoritative 4.0.4 release

This fix appears related but doesn't appear to fix this issue.
