### ISSUE TITLE
./configure issue on FreeBSD for recursor 4.0.5

### ISSUE THREAD

**Issue by RvdE** [PowerDNS/pdns#5401]
- Program: Recursor
 - Issue type: Bug report

### Short description
When running configure on FreeBSD it fails with the following error:
./configure: 2: Syntax error: Unterminated quoted string
./configure: 15888: Syntax error: Error in command substitution

### Environment

 - Operating system: FreeBSD 11.0
 - Software version: 4.0.5
 - Software source: PowerDNS repository

### Steps to reproduce

1. ./configure

### Other information
As requested by Peter (Habbie on IRC), this is to blame:
commit 6484f26 pieterlexis: Check if we can link against libatomic if needed https://git.io/vH5SS

**Comment by tjikkun** [comment]
This also prevent the Fedora build to succeed, because ppc64 and ppc64le are broken by this.

**Comment by Habbie** [comment]
```sh
  case "$host" in
  mips* | powerpc* )
    as_CACHEVAR=`$as_echo "ax_cv_check_ldflags_cannot continue" "$LINENO" 5
    _-latomic" | $as_tr_sh`
{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether the linker accepts -latomic" >&5
$as_echo_n "checking whether the linker accepts -latomic... " >&6; }
```

is the offending bit - line 15888 in the tarball.

**Comment by Habbie** [comment]
Fixed in #5411

**Comment by danel1** [comment]
Build is still broken on FreeBSD 10.3, even when applying the patch of #5411 

> checking dynamic linker characteristics... freebsd10.3 ld.so
> checking how to hardcode library paths into programs... immediate
> ./configure: 2: Syntax error: Unterminated quoted string
> ./configure: 15888: Syntax error: Error in command substitution

`[ AC_MSG_ERROR([Unable to link against libatomic, cannot continue]) ]`

**Comment by Habbie** [comment]
@danel1 after applying the patch, you need to run `autoreconf -vfi`
